"""The M1B schema, against a real PostgreSQL.

Why these are integration tests rather than unit tests: every property asserted
here is enforced by PostgreSQL, not by Python. A CHECK constraint that was
written but never applied, a UNIQUE that silently permits duplicates because of
NULL semantics, or a partial index whose predicate does not match the reaper's
query are all invisible to any test that does not talk to a real database.

They also exercise the actual `alembic upgrade` path rather than
`metadata.create_all()`. Those two can drift -- an autogenerated migration that
omits a constraint would still produce a passing `create_all()` test while
production got a table without it.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from uuid import UUID

import pytest
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

pytestmark = pytest.mark.integration

PROJECT_ROOT = Path(__file__).resolve().parents[2]

U = UUID("11111111-1111-7111-8111-111111111111")
C = UUID("22222222-2222-7222-8222-222222222222")


def _alembic(dsn: str, *args: str) -> subprocess.CompletedProcess[str]:
    """Run the real alembic CLI, the way `make migrate` does."""
    env = {**os.environ, "DATABASE_URL": dsn, "APP_ENV": "dev"}
    return subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=PROJECT_ROOT,
        env=env,
        capture_output=True,
        text=True,
    )


@pytest.fixture(scope="module")
async def migrated_dsn(postgres_dsn: str) -> str:
    result = _alembic(postgres_dsn, "upgrade", "head")
    assert result.returncode == 0, result.stdout + result.stderr
    return postgres_dsn


@pytest.fixture
async def seeded(migrated_dsn: str):
    """One user and one conversation, seeded idempotently.

    The engine is function-scoped deliberately: an asyncpg connection pool is
    bound to the event loop that created it, and pytest-asyncio gives each test
    its own loop, so a shared engine fails with "attached to a different loop".
    The seed is therefore ON CONFLICT DO NOTHING rather than a one-shot insert.
    """
    engine = create_async_engine(migrated_dsn)
    async with engine.begin() as conn:
        await conn.execute(
            text(
                "INSERT INTO users(id, display_name) VALUES (:u, 'Karunya')"
                " ON CONFLICT (id) DO NOTHING"
            ),
            {"u": U},
        )
        await conn.execute(
            text(
                "INSERT INTO conversations(id, user_id) VALUES (:c, :u) ON CONFLICT (id) DO NOTHING"
            ),
            {"c": C, "u": U},
        )
    yield engine
    await engine.dispose()


async def test_migration_creates_exactly_the_m1b_tables(migrated_dsn: str) -> None:
    """The milestone's table list is a decision, so it is asserted.

    A table appearing here early (say `notes`, which belongs to M1C) means
    scope has leaked into this migration.
    """
    engine = create_async_engine(migrated_dsn)
    try:
        async with engine.connect() as conn:
            rows = await conn.execute(
                text(
                    "SELECT table_name FROM information_schema.tables "
                    "WHERE table_schema='public' ORDER BY table_name"
                )
            )
            tables = {r[0] for r in rows}
    finally:
        await engine.dispose()

    assert tables == {
        "alembic_version",
        "system_settings",  # M1A
        "users",
        "identities",
        "conversations",
        "messages",
        "agent_runs",
        "llm_calls",
    }


async def test_role_check_rejects_unknown_roles(seeded) -> None:
    async with seeded.begin() as conn:
        with pytest.raises(Exception, match="ck_messages_role_valid"):
            await conn.execute(
                text(
                    "INSERT INTO messages(id, conversation_id, user_id, role, content,"
                    " provider, sent_at) VALUES (gen_random_uuid(), :c, :u, 'wizard',"
                    " 'x', 'cli', now())"
                ),
                {"c": C, "u": U},
            )


async def test_a_run_cannot_be_terminal_without_an_end_time(seeded) -> None:
    """The constraint that stops a crash from leaving 'completed but running'."""
    async with seeded.begin() as conn:
        with pytest.raises(Exception, match="ck_agent_runs_terminal_iff_completed"):
            await conn.execute(
                text(
                    "INSERT INTO agent_runs(id, conversation_id, user_id, state, started_at)"
                    " VALUES (gen_random_uuid(), :c, :u, 'complete', now())"
                ),
                {"c": C, "u": U},
            )


async def test_a_live_run_cannot_have_an_end_time(seeded) -> None:
    """The same constraint, the other direction."""
    async with seeded.begin() as conn:
        with pytest.raises(Exception, match="ck_agent_runs_terminal_iff_completed"):
            await conn.execute(
                text(
                    "INSERT INTO agent_runs(id, conversation_id, user_id, state, started_at,"
                    " completed_at) VALUES (gen_random_uuid(), :c, :u, 'model_calling',"
                    " now(), now())"
                ),
                {"c": C, "u": U},
            )


async def test_redelivered_provider_message_is_rejected(seeded) -> None:
    """The idempotency key (§11.4). This is the database-level protection
    against a duplicate assistant reply."""
    insert = text(
        "INSERT INTO messages(id, conversation_id, user_id, role, content, provider,"
        " provider_message_id, sent_at) VALUES (gen_random_uuid(), :c, :u, 'user',"
        " :body, 'cli', 'tg-99', now())"
    )
    async with seeded.begin() as conn:
        await conn.execute(insert, {"c": C, "u": U, "body": "hello"})
    async with seeded.begin() as conn:
        with pytest.raises(Exception, match="conversation_id_provider_message_id"):
            await conn.execute(insert, {"c": C, "u": U, "body": "hello again"})


async def test_locally_authored_messages_do_not_collide(seeded) -> None:
    """Assistant messages carry no provider id. Many NULLs must coexist, which
    is why this is a plain UNIQUE and relies on PostgreSQL's NULL semantics."""
    async with seeded.begin() as conn:
        await conn.execute(
            text(
                "INSERT INTO messages(id, conversation_id, user_id, role, content, provider,"
                " sent_at) VALUES (gen_random_uuid(), :c, :u, 'assistant', 'a', 'cli', now()),"
                " (gen_random_uuid(), :c, :u, 'assistant', 'b', 'cli', now())"
            ),
            {"c": C, "u": U},
        )
        count = await conn.scalar(
            text("SELECT count(*) FROM messages WHERE conversation_id = :c"), {"c": C}
        )
    assert count >= 2


async def test_reaper_index_is_partial_on_non_terminal_states(migrated_dsn: str) -> None:
    """§5.3: the reaper's index must stay small forever, which means it must
    not cover the terminal rows that make up ~all of history."""
    engine = create_async_engine(migrated_dsn)
    try:
        async with engine.connect() as conn:
            indexdef = await conn.scalar(
                text("SELECT indexdef FROM pg_indexes WHERE indexname = :n"),
                {"n": "ix_agent_runs_state_started_at"},
            )
    finally:
        await engine.dispose()

    assert indexdef is not None
    assert "WHERE" in indexdef
    for terminal in ("complete", "failed", "timed_out"):
        assert terminal in indexdef


async def test_downgrade_removes_the_m1b_tables(postgres_dsn: str) -> None:
    """A migration that cannot be undone is a migration you cannot test twice.

    Uses its own database so it does not tear down the module's fixture.
    """
    up = _alembic(postgres_dsn, "upgrade", "head")
    assert up.returncode == 0, up.stdout + up.stderr
    down = _alembic(postgres_dsn, "downgrade", "0001")
    assert down.returncode == 0, down.stdout + down.stderr

    engine = create_async_engine(postgres_dsn)
    try:
        async with engine.connect() as conn:
            rows = await conn.execute(
                text("SELECT table_name FROM information_schema.tables WHERE table_schema='public'")
            )
            tables = {r[0] for r in rows}
    finally:
        await engine.dispose()

    assert "agent_runs" not in tables
    assert "system_settings" in tables  # M1A survives
