"""conversation core: users, identities, conversations, messages, agent_runs, llm_calls

The M1B schema -- exactly the six tables ARCHITECTURE_v0.2 §11.1 assigns to this
milestone, no more. `notes`, `tool_calls` and `audit_log` belong to M1C and are
not created here; provenance/origin columns on `messages` and actor/ceiling
columns on `agent_runs` arrive with the policy engine at M1C (v0.3.1 §K).

Three things here are load-bearing rather than incidental:

  - `uq_messages_conversation_id_provider_message_id` is the idempotency key
    (§11.4): a redelivered inbound message becomes a database error instead of
    a duplicate assistant reply.
  - `ix_agent_runs_state_started_at` is partial on non-terminal states. It is
    the reaper's query (§5.3) and must stay small no matter how much history
    accumulates.
  - `ck_agent_runs_terminal_iff_completed` refuses to represent a run that is
    both finished and unfinished -- the corruption a crash mid-turn would
    otherwise leave behind.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-19 02:05:10.580892
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_user_id_last_message_at', 'conversations', ['user_id', 'last_message_at'], unique=False)
    op.create_table('identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identities')),
    sa.UniqueConstraint('provider', 'external_id', name='provider_external_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('created_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name=op.f('ck_messages_role_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_run_id'], ['agent_runs.id'], name=op.f('fk_messages_created_by_run_id_agent_runs'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'provider_message_id', name='conversation_id_provider_message_id')
    )
    op.create_index('ix_messages_conversation_id_sent_at', 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_message_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('failure_kind', sa.String(length=64), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('total_cost_micros', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(state IN ('complete', 'failed', 'timed_out')) = (completed_at IS NOT NULL)", name=op.f('ck_agent_runs_terminal_iff_completed')),
    sa.CheckConstraint("state IN ('received', 'context_building', 'model_calling', 'model_retry_wait', 'responding', 'complete', 'failed', 'timed_out')", name=op.f('ck_agent_runs_state_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_runs_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['messages.id'], name=op.f('fk_agent_runs_trigger_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_runs_conversation_id_started_at', 'agent_runs', ['conversation_id', 'started_at'], unique=False)
    op.create_index('ix_agent_runs_state_started_at', 'agent_runs', ['state', 'started_at'], unique=False, postgresql_where=sa.text("state NOT IN ('complete', 'failed', 'timed_out')"))
    op.create_table('llm_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('context_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('prompt_digest', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('tokens_cached', sa.Integer(), nullable=True),
    sa.Column('cost_micros', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('error_kind', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_llm_calls_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls')),
    sa.UniqueConstraint('run_id', 'step_no', name='run_id_step_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_calls')
    op.drop_index('ix_agent_runs_state_started_at', table_name='agent_runs', postgresql_where=sa.text("state NOT IN ('complete', 'failed', 'timed_out')"))
    op.drop_index('ix_agent_runs_conversation_id_started_at', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_messages_conversation_id_sent_at', table_name='messages')
    op.drop_table('messages')
    op.drop_table('identities')
    op.drop_index('ix_conversations_user_id_last_message_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
